"""
Week 1 Task — Backend Development with FastAPI and Python
Zaptek Research Brief

A complete backend API system built with FastAPI, using mock/sample data
(in-memory, no real database) to demonstrate:
  - API architecture & routing
  - CRUD operations
  - Request validation (via Pydantic)
  - Structured error handling

Run locally:
    pip install -r requirements.txt
    uvicorn main:app --reload

Interactive docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs      (Swagger UI)
    http://127.0.0.1:8000/redoc     (ReDoc)
"""

from typing import Optional

from fastapi import FastAPI, HTTPException, Query, status
from fastapi.middleware.cors import CORSMiddleware

from data import applications_db, get_next_id, now_iso
from models import Application, ApplicationCreate, ApplicationUpdate, StatusEnum

app = FastAPI(
    title="Applications API",
    description=(
        "A mock backend for managing program applications. Built for Zaptek's "
        "Week 1 Task: Backend Development with FastAPI and Python. Data is stored "
        "in-memory (no real database) and resets when the server restarts."
    ),
    version="1.0.0",
)

# Allow any origin to call this API — convenient for demoing the hosted endpoint.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def _find_application(app_id: int) -> dict:
    """Look up an application by id or raise a 404."""
    for application in applications_db:
        if application["id"] == app_id:
            return application
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Application with id {app_id} not found.",
    )


@app.get("/", tags=["Health"])
def root():
    """Basic health check / welcome route."""
    return {
        "message": "Applications API is running.",
        "docs": "/docs",
        "endpoints": {
            "list_all": "GET /applications",
            "get_one": "GET /applications/{id}",
            "create": "POST /applications",
            "update": "PUT /applications/{id}",
            "delete": "DELETE /applications/{id}",
        },
    }


@app.get("/applications", response_model=list[Application], tags=["Applications"])
def list_applications(
    status_filter: Optional[StatusEnum] = Query(
        None, alias="status", description="Filter by application status."
    ),
    university: Optional[str] = Query(
        None, description="Filter by university (case-insensitive, partial match)."
    ),
    track: Optional[str] = Query(
        None, description="Filter by track (case-insensitive, partial match)."
    ),
):
    """
    Get all applications. Supports optional filtering by status, university, and track.
    """
    results = applications_db

    if status_filter is not None:
        results = [a for a in results if a["status"] == status_filter.value]

    if university is not None:
        needle = university.lower()
        results = [a for a in results if needle in a["university"].lower()]

    if track is not None:
        needle = track.lower()
        results = [a for a in results if needle in a["track"].lower()]

    return results


@app.get("/applications/{app_id}", response_model=Application, tags=["Applications"])
def get_application(app_id: int):
    """Get a single application by its id."""
    return _find_application(app_id)


@app.post(
    "/applications",
    response_model=Application,
    status_code=status.HTTP_201_CREATED,
    tags=["Applications"],
)
def create_application(payload: ApplicationCreate):
    """Create a new application. `id` and `submittedAt` are generated by the server."""
    new_application = payload.model_dump(mode="json")
    new_application["id"] = get_next_id()
    new_application["submittedAt"] = now_iso()
    applications_db.append(new_application)
    return new_application


@app.put("/applications/{app_id}", response_model=Application, tags=["Applications"])
def update_application(app_id: int, payload: ApplicationUpdate):
    """
    Update an existing application. Only the fields provided in the request body
    are changed; omitted fields keep their current value.
    """
    existing = _find_application(app_id)
    updates = payload.model_dump(mode="json", exclude_unset=True)

    if not updates:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No fields provided to update.",
        )

    existing.update(updates)
    return existing


@app.delete("/applications/{app_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["Applications"])
def delete_application(app_id: int):
    """Delete an application by its id."""
    existing = _find_application(app_id)
    applications_db.remove(existing)
    return None
