"""
Pydantic models (schemas) for the Applications API.

We define three flavors of the same resource:
  - ApplicationBase   -> shared fields
  - ApplicationCreate -> fields required when creating a new application (no id/submittedAt,
                          those are generated by the server)
  - ApplicationUpdate -> all fields optional, used for partial updates (PATCH-style via PUT)
  - Application       -> the full resource as stored/returned, including id + submittedAt
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, EmailStr, Field, HttpUrl


class StatusEnum(str, Enum):
    pending = "pending"
    accepted = "accepted"
    rejected = "rejected"


class ApplicationBase(BaseModel):
    fullName: str = Field(..., min_length=2, max_length=100, examples=["Ama Serwaa Owusu"])
    email: EmailStr = Field(..., examples=["amaserwaa@gmail.com"])
    phone: str = Field(..., pattern=r"^0\d{9}$", examples=["0245567812"])
    whatsappNumber: str = Field(..., pattern=r"^0\d{9}$", examples=["0245567812"])

    university: str = Field(..., min_length=2, max_length=150, examples=["University of Ghana"])
    course: str = Field(..., min_length=2, max_length=150, examples=["Computer Engineering"])
    level: str = Field(..., examples=["2nd Year"])
    track: str = Field(..., examples=["Embedded Systems"])

    motivation: str = Field(..., min_length=10, max_length=1000)

    portfolioLink: Optional[HttpUrl] = None
    resumeLink: Optional[HttpUrl] = None

    joinInnovationClub: bool = False
    status: StatusEnum = StatusEnum.pending


class ApplicationCreate(ApplicationBase):
    """Payload for POST /applications — id and submittedAt are server-generated."""
    pass


class ApplicationUpdate(BaseModel):
    """Payload for PUT/PATCH /applications/{id} — every field optional (partial update)."""
    fullName: Optional[str] = Field(None, min_length=2, max_length=100)
    email: Optional[EmailStr] = None
    phone: Optional[str] = Field(None, pattern=r"^0\d{9}$")
    whatsappNumber: Optional[str] = Field(None, pattern=r"^0\d{9}$")

    university: Optional[str] = None
    course: Optional[str] = None
    level: Optional[str] = None
    track: Optional[str] = None

    motivation: Optional[str] = Field(None, min_length=10, max_length=1000)

    portfolioLink: Optional[HttpUrl] = None
    resumeLink: Optional[HttpUrl] = None

    joinInnovationClub: Optional[bool] = None
    status: Optional[StatusEnum] = None


class Application(ApplicationBase):
    id: int
    submittedAt: datetime

    class Config:
        from_attributes = True
